---
title: "What I learned at posit::conf 2024"
author: "Jeremy McWilliams"
format: revealjs
---

## posit::2024 conference

- August 12-14
- Seattle, WA

## Data Scientists LOVE Quarto

- Why?
- Many are tasked with creating outputs:
-- reports (html, pdf)
-- data dashboards
- Quarto's purpose is just that: publishing work for stakeholders

## Should you "switch" to Quarto?
- It depends
- For writing code in R or Python, it doesn't give you anything more (.Rmd, .R, .ipynb are fine)
- If you want students to create outputs (websites, reports, data dashboards), then yes


## More on Quarto
::: {.incremental}
- For certain outputs (websites, data dashboards), knowing HTML/CSS is important
- Emphasis on "making things look nice" for stakeholders => command of HTML/CSS
- Presenters seemed to learn on their own. Should we include this in curriculum?
:::


## Positron
- Positron is a Desktop Integrated Development Environment (IDE) in development by the posit team
- It's based on the open source "Code OSS" (so is VS Code, which is why it looks similar)
- They did it because of their intention to support *and run* many languages (Python, Julia, etc.)
- RStudio's architecture doesn't allow for multiple language kernels, hence their decision to make Positron

## Positron vs. RStudio/posit.cloud
- They're planning to support both programs moving ahead
- There was no mention of a cloud-based system for Positron -- I'm guessing perhaps, but not anytime soon
- posit.cloud has worked well for us, so no need to switch
- with that said, it looks awesome. Great support for multiple languages, DB integration/explorer
- In industry, it seems like many use Desktop apps (e.g. RStudio, VS Code)


## Johns Hopkins Social Good Class
- Partnered with Baltimore Community Based Organizations
- 1st half - Students learned initially how to work with CBOs
- 2nd half - Students worked on specific projects to support CBOs
- Lots of writing and discussion, some data science
- Course: https://jhudatascience.org/Baltimore_Community_Course/

## DuckDB
- package for R, python, and other languages to add db/sql functionality
- supposedly very fast at querying huge csv files
- stores data on disc instead of just on memory
- could be a good/easy gateway for including SQL


## Other Take-homes
- EVERYONE uses GitHub
- Lots of excitement around automating reports for stakeholders, using "quarto parameters"
- Data Science community is very welcoming, supportive, eager to share ideas



## Things to consider at LC
- Should we add more end-products in curriculum (i.e. Quarto reports/dashboards)?
- Can we incorporate GitHub more?
- Can we connect with local stakeholders to give students more experiences?


